# 数据清洗与准备

## 7.1处理缺失值

In [2]:
import pandas as pd
import numpy as np

In [3]:
string_data=pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [4]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data[0]=None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 7.1.1过滤缺失值

In [7]:
from numpy import nan as NA 

In [8]:
data=pd.Series([1,NA,3.5,NA,7])

In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data=pd.DataFrame([[1.,6.5,3.],[1,NA,NA],[NA,NA,NA],[NA,6.5,3.]])

In [12]:
cleaned=data.dropna()

In [13]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4]=NA

In [17]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [18]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
df=pd.DataFrame(np.random.randn(7,3))

In [20]:
df.iloc[:4,1]=NA

In [21]:
df.iloc[:2,2]=NA

In [22]:
df

0         1         2
0 -0.347551       NaN       NaN
1  0.539904       NaN       NaN
2  1.033247       NaN -0.982708
3 -0.758251       NaN  1.432976
4 -0.644270 -0.248319  0.378181
5 -0.768003  0.875713  0.063879
6  0.432000 -1.494716 -0.644604

In [23]:
df.dropna()

0         1         2
4 -0.644270 -0.248319  0.378181
5 -0.768003  0.875713  0.063879
6  0.432000 -1.494716 -0.644604

In [24]:
df.dropna(thresh=2)

0         1         2
2  1.033247       NaN -0.982708
3 -0.758251       NaN  1.432976
4 -0.644270 -0.248319  0.378181
5 -0.768003  0.875713  0.063879
6  0.432000 -1.494716 -0.644604

### 7.1.2补全缺失值

In [25]:
df.fillna(0)

0         1         2
0 -0.347551  0.000000  0.000000
1  0.539904  0.000000  0.000000
2  1.033247  0.000000 -0.982708
3 -0.758251  0.000000  1.432976
4 -0.644270 -0.248319  0.378181
5 -0.768003  0.875713  0.063879
6  0.432000 -1.494716 -0.644604

In [27]:
df.fillna({1:0.5,2:0})#使用字典为不同列设定不同填充值

0         1         2
0 -0.347551  0.500000  0.000000
1  0.539904  0.500000  0.000000
2  1.033247  0.500000 -0.982708
3 -0.758251  0.500000  1.432976
4 -0.644270 -0.248319  0.378181
5 -0.768003  0.875713  0.063879
6  0.432000 -1.494716 -0.644604

In [28]:
_=df.fillna(0,inplace=True)

In [29]:
df

0         1         2
0 -0.347551  0.000000  0.000000
1  0.539904  0.000000  0.000000
2  1.033247  0.000000 -0.982708
3 -0.758251  0.000000  1.432976
4 -0.644270 -0.248319  0.378181
5 -0.768003  0.875713  0.063879
6  0.432000 -1.494716 -0.644604

In [30]:
df=pd.DataFrame(np.random.randn(6,3))

In [31]:
df.iloc[2:,1]=NA
df.iloc[4:,2]=NA

In [32]:
df

0         1         2
0 -1.020038  0.472508 -0.805678
1 -1.721763 -0.043387  0.439773
2 -0.536646       NaN  1.235902
3 -1.062833       NaN  0.544369
4 -0.697260       NaN       NaN
5 -0.755309       NaN       NaN

In [33]:
df.fillna(method='ffill')

0         1         2
0 -1.020038  0.472508 -0.805678
1 -1.721763 -0.043387  0.439773
2 -0.536646 -0.043387  1.235902
3 -1.062833 -0.043387  0.544369
4 -0.697260 -0.043387  0.544369
5 -0.755309 -0.043387  0.544369

In [34]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -1.020038  0.472508 -0.805678
1 -1.721763 -0.043387  0.439773
2 -0.536646 -0.043387  1.235902
3 -1.062833 -0.043387  0.544369
4 -0.697260       NaN  0.544369
5 -0.755309       NaN  0.544369

In [35]:
data=pd.Series([1.,NA,3.5,NA,7])

In [36]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2数据转换

In [37]:
data=pd.DataFrame({'k1':['one','two']*3+['two'],
                  'k2':[1,1,2,3,3,4,4]})

In [38]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [39]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [40]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [41]:
data['v1']=range(7)

In [42]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [43]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 7.2.2使用函数或映射进行数据转换

In [48]:
data=pd.DataFrame({'food':['bacon','pulled pork','bacon','pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],
      'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [49]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [50]:
meat_to_animal={
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [51]:
lowercased=data['food'].str.lower()

In [52]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [53]:
data['animal']=lowercased.map(meat_to_animal)

In [54]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [55]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 7.2.3替代值

In [57]:
data=pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [58]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [59]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [61]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [62]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [63]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 7.2.4重命名轴索引

In [64]:
data=pd.DataFrame(np.arange(12).reshape((3,4)),
                 index=['Ohio','Colorado','New York'],
                 columns=['one','two','three','four'])

In [65]:
transform=lambda x:x[:4].upper()

In [66]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [67]:
data.index=data.index.map(transform)

In [69]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [70]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [71]:
data.rename(index={'OHIO':"INDIANA"},
           columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [72]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [73]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### 7.2.5离散化和分箱

In [74]:
age=[20,22,25,27,21,23,37,31,61,45,41,32]

In [75]:
bins=[18,25,35,60,100]

In [77]:
cats=pd.cut(age,bins)

In [78]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [79]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [80]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [81]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [82]:
pd.cut(age,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [83]:
group_names=['Youth','YouthAdult','MiddleAged','Senior']

In [84]:
pd.cut(age,bins,labels=group_names)

[Youth, Youth, Youth, YouthAdult, Youth, ..., YouthAdult, Senior, MiddleAged, MiddleAged, YouthAdult]
Length: 12
Categories (4, object): [Youth < YouthAdult < MiddleAged < Senior]

In [85]:
data=np.random.rand(20)
pd.cut(data,4,precision=2)

[(0.53, 0.76], (0.073, 0.3], (0.3, 0.53], (0.76, 0.99], (0.073, 0.3], ..., (0.3, 0.53], (0.76, 0.99], (0.3, 0.53], (0.3, 0.53], (0.53, 0.76]]
Length: 20
Categories (4, interval[float64]): [(0.073, 0.3] < (0.3, 0.53] < (0.53, 0.76] < (0.76, 0.99]]

In [86]:
data=np.random.randn(1000)

In [87]:
cats=pd.qcut(data,4)

In [88]:
cats

[(-0.636, -0.0333], (0.658, 3.401], (-0.0333, 0.658], (-0.0333, 0.658], (0.658, 3.401], ..., (-3.0349999999999997, -0.636], (-0.636, -0.0333], (0.658, 3.401], (-0.0333, 0.658], (-3.0349999999999997, -0.636]]
Length: 1000
Categories (4, interval[float64]): [(-3.0349999999999997, -0.636] < (-0.636, -0.0333] < (-0.0333, 0.658] < (0.658, 3.401]]

In [89]:
pd.value_counts(cats)

(0.658, 3.401]                   250
(-0.0333, 0.658]                 250
(-0.636, -0.0333]                250
(-3.0349999999999997, -0.636]    250
dtype: int64

In [90]:
pd.qcut(data,[0,0.1,0.5,0.9,1.])

[(-1.319, -0.0333], (1.278, 3.401], (-0.0333, 1.278], (-0.0333, 1.278], (1.278, 3.401], ..., (-1.319, -0.0333], (-1.319, -0.0333], (1.278, 3.401], (-0.0333, 1.278], (-1.319, -0.0333]]
Length: 1000
Categories (4, interval[float64]): [(-3.0349999999999997, -1.319] < (-1.319, -0.0333] < (-0.0333, 1.278] < (1.278, 3.401]]

### 7.2.6检测和过滤异常值

In [92]:
data=pd.DataFrame(np.random.randn(1000,4))

In [93]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.009395     0.021410     0.001160     0.035228
std       0.969593     1.006041     1.002081     0.963555
min      -3.171531    -3.089771    -3.311452    -3.065584
25%      -0.671921    -0.679912    -0.654463    -0.618985
50%       0.003420     0.015185     0.041356     0.060981
75%       0.661257     0.707248     0.643053     0.658637
max       3.043105     3.753950     3.061337     3.256830

In [94]:
col=data[2]

In [95]:
col[np.abs(col)>3]

115   -3.311452
246    3.061337
Name: 2, dtype: float64

In [96]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
115 -0.023486 -0.133790 -3.311452 -0.212223
224  3.043105 -1.014116  0.612468  1.773310
246 -0.882816 -1.659622  3.061337  1.510366
360  3.018493  0.089469  0.162307 -0.504460
495  0.061342  0.961840  1.724377 -3.065584
583 -1.230749  3.040764 -0.964625  1.125943
658 -1.999887  1.258108  0.572815  3.256830
705 -1.015833  3.753950 -1.377699 -1.286233
780 -3.171531  0.246289  0.505355 -1.201787
813 -0.736846  0.289353  0.595747  3.171912
870  1.399347 -3.089771  0.624210  0.469854

In [97]:
data[np.abs(data)>3]=np.sign(data)*3

In [98]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.009285     0.020705     0.001410     0.034864
std       0.968856     1.003123     1.000912     0.961975
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.671921    -0.679912    -0.654463    -0.618985
50%       0.003420     0.015185     0.041356     0.060981
75%       0.661257     0.707248     0.643053     0.658637
max       3.000000     3.000000     3.000000     3.000000

In [99]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1 -1.0  1.0  1.0  1.0
2 -1.0 -1.0 -1.0  1.0
3 -1.0 -1.0  1.0 -1.0
4  1.0  1.0  1.0  1.0

### 7.2.7置换和随机抽样

In [100]:
df=pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [102]:
sampler=np.random.permutation(5)#随机重排序

In [103]:
sampler

array([0, 1, 4, 2, 3])

In [104]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [105]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11
3  12  13  14  15

In [106]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11

In [107]:
choices=pd.Series([5,7,-1,6,4])

In [108]:
draws=choices.sample(n=10,replace=True)

In [109]:
draws

1    7
4    4
2   -1
1    7
1    7
4    4
3    6
2   -1
1    7
1    7
dtype: int64

### 7.2.8计算指标/虚拟变量


In [110]:
df=pd.DataFrame({'key':['b','b','a','c','a','b'],
                'data1':range(6)})

In [111]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [112]:
dummies=pd.get_dummies(df['key'],prefix='key')

In [113]:
df_with_dummy=df[['data1']].join(dummies)

In [114]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [115]:
mnames=['movie_id','title','genres']

In [116]:
movies=pd.read_table('movies.dat',sep='::',header=None,names=mnames)

H:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [118]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [119]:
all_genres=[]

In [120]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [121]:
all_genres

['Animation',
 "Children's",
 'Comedy',
 'Adventure',
 "Children's",
 'Fantasy',
 'Comedy',
 'Romance',
 'Comedy',
 'Drama',
 'Comedy',
 'Action',
 'Crime',
 'Thriller',
 'Comedy',
 'Romance',
 'Adventure',
 "Children's",
 'Action',
 'Action',
 'Adventure',
 'Thriller',
 'Comedy',
 'Drama',
 'Romance',
 'Comedy',
 'Horror',
 'Animation',
 "Children's",
 'Drama',
 'Action',
 'Adventure',
 'Romance',
 'Drama',
 'Thriller',
 'Drama',
 'Romance',
 'Thriller',
 'Comedy',
 'Action',
 'Action',
 'Comedy',
 'Drama',
 'Crime',
 'Drama',
 'Thriller',
 'Thriller',
 'Drama',
 'Sci-Fi',
 'Drama',
 'Romance',
 'Drama',
 'Drama',
 'Romance',
 'Adventure',
 'Sci-Fi',
 'Drama',
 'Drama',
 'Drama',
 'Sci-Fi',
 'Adventure',
 'Romance',
 "Children's",
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Drama',
 'Documentary',
 'Comedy',
 'Comedy',
 'Romance',
 'Drama',
 'Drama',
 'War',
 'Action',
 'Crime',
 'Drama',
 'Drama',
 'Action',
 'Adventure',
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Crime',
 'Thrill

In [122]:
genres=pd.unique(all_genres)

In [123]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [124]:
zero_matrix=np.zeros((len(movies),len(genres)))

In [125]:
dummies=pd.DataFrame(zero_matrix,columns=genres)

In [126]:
gen=movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [127]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [129]:
for i,gen in enumerate(movies.genres):
    indices=dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices]=1

In [131]:
movies_windic=movies.join(dummies.add_prefix('Genre_'))

In [132]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [133]:
np.random.seed(12345)

In [134]:
values=np.random.rand(10)

In [135]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [136]:
bins=[0,0.2,0.4,0.6,0.8,1]

In [137]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 字符串操作

### 7.3.1字符串对象方法

In [138]:
val='a,b,  guido'

In [139]:
val.split(',')

['a', 'b', '  guido']

In [140]:
pieces=[x.strip() for x in val.split(',')]

In [141]:
pieces

['a', 'b', 'guido']

In [142]:
first,second,third=pieces

In [143]:
first+'::'+second+'::'+third

'a::b::guido'

In [144]:
'::'.join(pieces)

'a::b::guido'

In [145]:
'guido' in val

True

In [146]:
val.index(',')

1

In [147]:
val.find(':')

-1

In [148]:
val.count(',')

2

In [149]:
val.replace(',','::')

'a::b::  guido'

In [150]:
val.replace(',','')

'ab  guido'

### 7.3.2正则表达式

In [152]:
import re

In [153]:
text='foo   bar\t baz   \tqux'

In [154]:
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [155]:
regex=re.compile('\s+')


In [156]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [157]:
regex.findall(text)

['   ', '\t ', '   \t']

In [158]:
text='''Dave dave@google.com
Steve steve@google.com
Rob rob@gmail.com
Ryan ryan@yahoo.com

'''

In [161]:
pattern=r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex=re.compile(pattern)

In [162]:
regex.findall(text)

[]